import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import ReduxProvider from "@/providers/ReduxProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-ticaret App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}
      >
        <ReduxProvider>
          <div className="bg-[#e3dada] shadow-2xl">
            <div className="max-w-[1200px] mx-auto px-4">
              <Header />
            </div>
          </div>
          <main className="flex-1 min-h-0">
            <div className="max-w-[1200px] mx-auto px-4 h-full min-h-0">{children}</div>
          </main>
          <div className="max-w-[1200px] mx-auto px-4 h-20">
            <Footer />
          </div>
        </ReduxProvider>


      </body>
    </html>
  );
}
